version: "3"
services:
  human-api:
    build: .
    environment:
      - HMT_ETH_SERVER=https://dappnet-api.skalenodes.com/v1/rhythmic-sirius
      - GAS_PAYER=0x1413862C2B7054CDbfdc181B83962CB0FC11fD92
      - GAS_PAYER_PRIV=0x28e516f1e2f99e96a48a23cea1f94ee5f073403a1c68e818263f0eb898f1c8e5
      - REP_ORACLE_PUB_KEY=2dbc2c2c86052702e7c219339514b2e8bd4687ba1236c478ad41b43330b08488c12c8c1797aa181f3a4596a1bd8a0c18344ea44d6655f61fa73e56e743f79e0d
    links:
      - hmt-escrow
    ports:
      - 8080:8080
    volumes:
      - .:/work
      - hmt-escrow:/deployed-hmtoken
      - ./skale:/skale

  hmt-escrow:
    image: skalenetwork/hmt-escrow:skale-0.9.2
    environment:
      - HMT_ETH_SERVER=wss://dappnet-api.skalenodes.com/v1/ws/rhythmic-sirius
      - GAS_LIMIT=6700000
      - ESCROW_BUCKETNAME=escrow-results
      - ESCROW_AWS_ACCESS_KEY_ID=minio
      - ESCROW_AWS_SECRET_ACCESS_KEY=minio123
      - ESCROW_ENDPOINT_URL=http://minio:9000
      - ESCROW_AWS_DEFAULT_REGION=us-west-2
      - DEBUG=true
      - USE_ESCROW_S3_STORAGE=True
      - MNEMONIC=${MNEMONIC}
      - PRIV_KEY=${PRIV_KEY}
    depends_on:
      - minio
    volumes:
      - ./skale:/skale
      - ./minio:/data
      - hmt-escrow:/deployed-hmtoken
    command: sh -c "rm /deployed-hmtoken/hmt.address.json; curl --retry 10 --retry-connrefused --retry-max-time 10 https://dappnet-api.skalenodes.com/v1/rhythmic-sirius; npm install && truffle deploy --reset-all --network skale --compile-all"



  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    entrypoint: sh -c 'minio server /data/'
    volumes:
      - ./minio:/data

volumes:
  hmt-escrow:
