version: "3"
services:
  human-api:
    build: .
    environment:
      - HMT_ETH_SERVER=ws://ganache:8545
    depends_on:
      - ganache
    links:
      - ganache
    ports:
      - 8080:8080

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: node ./build/cli.node.js --noVMErrorsOnRPCResponse -m goat --hostname 0.0.0.0 --unlock 0x1413862c2b7054cdbfdc181b83962cb0fc11fd92 -g 1000
    ports:
      - 8545:8545