version: "3"
services:
  human-api:
    build: .
    environment:
      - HMT_ETH_SERVER=https://humanprotocol-integration.skale.network
      - GAS_PAYER=0x1413862C2B7054CDbfdc181B83962CB0FC11fD92
      - GAS_PAYER_PRIV=0x28e516f1e2f99e96a48a23cea1f94ee5f073403a1c68e818263f0eb898f1c8e5
      - REP_ORACLE_PUB_KEY=2dbc2c2c86052702e7c219339514b2e8bd4687ba1236c478ad41b43330b08488c12c8c1797aa181f3a4596a1bd8a0c18344ea44d6655f61fa73e56e743f79e0d
    links:
      - ganache
      - hmt-escrow
    ports:
      - 8080:8080
    volumes:
      - .:/work
      - hmt-escrow:/deployed-hmtoken

  hmt-escrow:
    image: humanprotocol/hmt-escrow:release-0.9.1
    environment:
      - HMT_ETH_SERVER=ws://humanprotocol-integration.skale.network
      - GAS_LIMIT=6700000
      - ETH_HOST=ganache
      - ETH_PORT=8545
      - ESCROW_BUCKETNAME=escrow-results
      - ESCROW_AWS_ACCESS_KEY_ID=minio
      - ESCROW_AWS_SECRET_ACCESS_KEY=minio123
      - ESCROW_ENDPOINT_URL=http://minio:9000
      - ESCROW_AWS_DEFAULT_REGION=us-west-2
      - DEBUG=true
      - USE_ESCROW_S3_STORAGE=True
      - MNEMONIC=${MNEMONIC}
      - PRIV_KEY=${PRIV_KEY}
    depends_on:
      - minio
      - ganache
    links:
      - ganache
    volumes:
      - ./minio:/data
      - hmt-escrow:/deployed-hmtoken
    command: sh -c "rm /deployed-hmtoken/hmt.address.json; curl --retry 10 --retry-connrefused --retry-max-time 10 https://humanprotocol-integration.skale.network; npm install && truffle deploy --reset-all --network skale --compile-all"

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: node /app/ganache-core.docker.cli.js --noVMErrorsOnRPCResponse -m goat --hostname 0.0.0.0 --unlock 0x1413862c2b7054cdbfdc181b83962cb0fc11fd92 -g 1000 -f https://humanprotocol-integration.skale.network
    ports:
      - 8545:8545

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    entrypoint: sh -c 'minio server /data/'
    volumes:
      - ./minio:/data

volumes:
  hmt-escrow:
